services:
  postgres-db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  service:
    container_name: virtual-gamers-service
    build:
      context: ./virtual-gamers-service
      dockerfile: Dockerfile
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    depends_on:
      - postgres-db
    networks:
      - my_network
    environment:
      PORT: ${SERVICE_PORT}
      REACT_APP_PORT: ${REACT_APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT_INTERNAL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: development  # Set environment variables if needed

  react-app:
    container_name: virtual-gamers-react-app
    build:
      context: ./virtual-gamers-react-app
      args:
        REACT_APP_PORT: ${REACT_APP_PORT}
        REACT_APP_SERVICE_API: ${SERVICE_API}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    environment:
      NODE_ENV: production
    depends_on:
      - service

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
