services:
  postgres-db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT_INTERNAL}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - my_network

  redis:
    container_name: virtual-gamers-redis
    image: redis
    networks:
      - my_network
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}

  ruby-service:
    container_name: virtual-gamers-ruby-service
    build:
      context: ./virtual-gamers-ruby-service
      dockerfile: Dockerfile
    ports:
      - ${RUBY_SERVICE_PORT}:${RUBY_SERVICE_PORT}
    depends_on:
      - postgres-db
    networks:
      - my_network
    environment:
      PORT: ${RUBY_SERVICE_PORT}
      REACT_APP_URL: ${REACT_APP_URL}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT_INTERNAL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      REDIS_URL: ${REDIS_URL}

  nodejs-service:
    container_name: virtual-gamers-nodejs-service
    build:
      context: ./virtual-gamers-nodejs-service
      dockerfile: Dockerfile
    ports:
      - ${NODEJS_SERVICE_PORT}:${NODEJS_SERVICE_PORT}
    depends_on:
      - postgres-db
    networks:
      - my_network
    environment:
      PORT: ${NODEJS_SERVICE_PORT}
      REACT_APP_PORT: ${REACT_APP_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT_INTERNAL}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      NODE_ENV: development # Set environment variables if needed

  react-app:
    container_name: virtual-gamers-react-app
    build:
      context: ./virtual-gamers-react-app
      args:
        REACT_APP_PORT: ${REACT_APP_PORT}
        REACT_APP_NODEJS_SERVICE_API: ${NODEJS_SERVICE_API}
        REACT_APP_RUBY_SERVICE_API: ${RUBY_SERVICE_API}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    environment:
      NODE_ENV: production
    depends_on:
      - ruby-service
      - nodejs-service

networks:
  my_network:
    driver: bridge

volumes:
  postgres_data:
